### ISSUE TITLE
Add a launcher icon for Android client

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-android-client#3]
We could use the attached file if its quality is ok.

![freedomotic](https://user-images.githubusercontent.com/4079634/31910408-a9ec7042-b83d-11e7-9e71-c15f3a0ae446.png)

**Comment by Hackertronix** [comment]
I'm taking this up

**Comment by moses-lee** [comment]
is help still needed?

**Comment by mcicolella** [comment]
The previous attached file is not very good because I noticed it's cropped and the background is white.
Here a new file with transparent background.
![logo_512](https://user-images.githubusercontent.com/4079634/31948034-10cf44cc-b8d6-11e7-89a9-93a422aee3a8.png)
@sathyapriya31 what about?

**Comment by sathyapriya31** [comment]
@mcicolella i will change now

**Comment by Hackertronix** [comment]
@mcicolella Created PR #17  with the updated asset that you have tagged above
